### ISSUE TITLE
Gracefully fail if one or more product details is not retreived

### ISSUE THREAD

**Issue by kristfal** [AlexDisler/cordova-plugin-inapppurchase#11]
Hey,

first – thanks for this sweet plugin. It's incredibly easy to work with and looking forward to finishing the transition from a rather cumbersome old iap plugin to this new and (so far) very nice plugin.

We're working with a lot of products, and some times we get product identifiers mixed up. This plugin currently throws an error message (tested on Android only) `Error retrieving SKU details`, without listing which products that failed. That could be a hassle to debug for new devs as there could be a whole range of reasons why some products may be invalid.

Steps to reproduce
```js

inAppPurchase.getProducts(['valid_identifier', 'invalid_identifier']);

```
Console output

`Error retrieving SKU details`

Type of product you are working with consumable/non-consumable/subscription

Subscription

Version of cordova

`6.1.0`

Version of iOS/Android

`Android, version 4.1.1`

Expected result:

Preferably: 
Response should contain an object with valid products in an array, and invalid products in a separate array.

Alternative:
Error should contain an object with invalid products.

**Comment by AlexDisler** [comment]
Hey, thanks for the suggestion. It's a good idea.

**Comment by AlexDisler** [comment]
@kristfal I'll close this issue for now since I won't have time to add this functionality anytime soon, but a PR is of course welcome.

**Comment by richardmarais** [comment]
I am getting the same error when `.getProducts(this.PRODUCT_IDS)`:

> Error retrieving SKU details

It was working perfectly, until I added a test user. I tried to make a purchase with the test user.

    this.iap.buy(item.productId).then((data) => {
      return this.iap.consume(data.productType, data.receipt, data.signature);
    }).then(() => {
      console.log('product was successfully consumed!');

But now I cannot access the products any longer.

I have read [here](https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/55) that the reason may be because testers cannot consume a product and offers this solution:

SOLUTION:
Pull up "orders" on the Play Console and "cancel" the pending purchase.

However, then I have two questions:

1. How do you test purchases, if a tester cannot consume a product?
2. Where do you pull up orders on the Play Console? I do look at "Order Management", but there are no orders listed.

Thanks

**Comment by Elakioui** [comment]
Hey, I am getting the same error with test account.
You found a solution for this problem :-)
