### ISSUE TITLE
Android: Error retrieving SKU details when retrieving 20 products or more

### ISSUE THREAD

**Issue by kristfal** [AlexDisler/cordova-plugin-inapppurchase#12]
Retrieving 20 or more products on Android will fail. Workaround for now is to slice the products into groups of 19 and promise chain the slices.

Code / steps to reproduce
```js

inAppPurchase.getProducts([Prod1, Prod2, ... , Prod20]).then((products) => {
				console.log(products);
			})
			.catch((error) => {
				console.log(error);
			});
```
Console output

```
Error retrieving SKU details
```

Type of product you are working with consumable/non-consumable/subscription

Tested with a mix of subscriptions and non-consumables

Version of cordova

6.1.0

Version of iOS/Android

Android 4.1.1

**Comment by AlexDisler** [comment]
This is a limitation of Google's API https://github.com/AlexDisler/cordova-plugin-inapppurchase/blob/master/src/android/billing/IInAppBillingService.aidl#L61

**Comment by kristfal** [comment]
Hey, if you don't mind, I can add a PR that slices the requests and chain them in order to support 20+ products.

**Comment by AlexDisler** [comment]
Hey, yeah sure, thanks

**Comment by richardmarais** [comment]
I am getting the same error when `.getProducts(this.PRODUCT_IDS)`:

> Error retrieving SKU details

It was working perfectly, until I added a test user. I tried to make a purchase with the test user.

    this.iap.buy(item.productId).then((data) => {
      return this.iap.consume(data.productType, data.receipt, data.signature);
    }).then(() => {
      console.log('product was successfully consumed!');

But now I cannot access the products any longer.

I have read [here](https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/55) that the reason may be because testers cannot consume a product and offers this solution:

SOLUTION:
Pull up "orders" on the Play Console and "cancel" the pending purchase.

However, then I have two questions:

1. How do you test purchases, if a tester cannot consume a product?
2. Where do you pull up orders on the Play Console? I do look at "Order Management", but there are no orders listed.

Thanks
