### ISSUE TITLE
Empty product array response in ios

### ISSUE THREAD

**Issue by komalW21** [AlexDisler/cordova-plugin-inapppurchase#190]
Please include:

### Your code / steps to reproduce
```js
  this.iap
          .getProducts(['test_consumable_product'])
            .then((products) => {
              console.log('Products:',products);
           
            }, Error => {})
          .catch((err) => {});
```
### Console output
Products: []
### Type of product you are working with consumable/non-consumable/subscription
Working with consumable products
### Version of cordova
Version of cordova - 7.0.1

**Comment by moritzgloeckl** [comment]
- Are you testing on a real device? In App purchases are not supported in emulators/simulators.
- Have you enabled In-App Purchases for your App ID?
- Have you checked Cleared for Sale for your product?
- Does your project’s .plist Bundle ID match your App ID?
- Have you generated and installed a new provisioning profile for the new App ID?
- Have you configured your project to code sign using this new provisioning profile?
- Have you waited several hours since adding your product to iTunes Connect?
- Have you tried deleting the app from your device and reinstalling?
- Have you accepted contracts for IAPs in iTunes connect?
- Is your device jailbroken? If so, you need to revert the jailbreak for IAP to work.

**Comment by komalW21** [comment]
- Are you testing on a real device? In App purchases are not supported in emulators/simulators. - yes
- Have you enabled In-App Purchases for your App ID? Yes
- Have you checked Cleared for Sale for your product? Yes, I checked on Clear for sale
- Does your project’s .plist Bundle ID match your App ID? Yes
- Have you generated and installed a new provisioning profile for the new App ID? I am using development provisioning profile for App Id
- Have you configured your project to code sign using this new provisioning profile? Yes, Using new development provisioning profile
- Have you waited several hours since adding your product to iTunes Connect? Yes. 
- Have you tried deleting the app from your device and reinstalling? Yes
- Have you accepted contracts for IAPs in iTunes connect? Yes
- Is your device jailbroken? If so, you need to revert the jailbreak for IAP to work. My device is not jailbroken

As I have created sandbox tester in itunes and make login in real device using that app id. Still I dont know what is missing in that.
