### ISSUE TITLE
Add concept of pending purchases requiring a confirmation callback

### ISSUE THREAD

**Issue by MStumpp** [AlexDisler/cordova-plugin-inapppurchase#22]
How about adding a callback to the buy()-function allowing to confirm a purchase?

Currently, a purchase takes place immediately when calling buy()-function. This works for purchase with local content. But just imagine the case when the app has to download extra content after the purchase, but there is some issue. The user still has bought the product but may not be able to access the purchased content.

Other plugins solve this by adding an extra callback to the buy()-function, which has to be called after the content is available.

**Comment by AlexDisler** [comment]
If the user has purchased something and the download failed (due to network issues etc), I let them re-try the download instead of canceling the purchase.

I would prefer to leave the current ```buy``` function as is to keep the api simple, but I think there could be another alternative ```conditionalBuy``` function that works with a callback as you described. A PR is of course welcome.

**Comment by biesbjerg** [comment]
I would love this feature as well! My use-case is:

1. Purchase a consumable
2. Make an API call to backend to add purchase to customer's account
3. If 2. is successful, complete purchase, if not, don't complete/cancel.

Looking at the code, it unfortunately seems to be above my skill level, since it requires changes to both Obj-C and Java code, if I'm not mistaken.

@MStumpp: Did you find a solution?

**Comment by kwizzn** [comment]
@AlexDisler, don't you already have this scenario for Android purchases that support the `consume()` method? We love the simplicity of this plugin but what @biesbjerg suggests is a perfectly valid flow: Have your API return whether the user has received is purchase.
