### ISSUE TITLE
getProducts doesn't work anymore after buying an item

### ISSUE THREAD

**Issue by Jenthe** [AlexDisler/cordova-plugin-inapppurchase#55]
Hey,

The plugin works fine until the moment I successfully finish a test purchase. After that the getProducts method return 'Error retrieving SKU details' and the restorePurchases method returns 'Error retrieving purchase details'. When I make a new test account that hasn't bought anything everything works as expected. 

Any idea what the problem could be, maybe because of the use of test accounts?

Please include:

### Your code / steps to reproduce
See above comment

### Console output
Error retrieving purchase details
Error retrieving SKU details

### Type of product you are working with consumable/non-consumable/subscription
Non-consumable items.

### Version of cordova
6.1.1

### Version of iOS/Android
Android: 5.1

**Comment by Jenthe** [comment]
It's solved, my own fault. I forgot to change the public billing key after changing the packet name. Strange that I was still able to buy an item with the old key.

**Comment by sujithsavithryma** [comment]
Hi , i got the same issue

**Comment by philipphalder** [comment]
Same issue here :-(

does anyone got experience with this plugin?  https://github.com/j3k0/cordova-plugin-purchase

**Comment by JohnScottMcNerney** [comment]
Same issue.... any resolution yet??

Truly frustrating. Worked perfectly, until setting my google email as a LICENSE TESTING in Google Play Developer Console -> Settings. 

1st thing was that I could get my product list, all comsumables, but when I tried to "buy" one of them I got "you already own this item", which as a consumable is just wrong. Another consumable returned a different error, and yet another did pull up a "purchase window" noting it was a test purchase.

I also added the "android.test.purchased" as a purchase option, and when clicked it seemed to run okay.

After all this, the getProducts is simply broken. Returning "Error retrieving SKU details".

Cleaned cordova. Re-installed OS X libraries. Re-built-re-uploaded new APK. Still broke......

- John :(

**Comment by philipphalder** [comment]
If you are an android you need to consume the product after purchasing. ;-)

**Comment by JohnScottMcNerney** [comment]
@philipphalder Thanks!

You are right, I must consume the purchase (or at least cancel it manually).

SOLUTION:
Pull up "orders" on the Play Console and "cancel" the pending purchase.

REASON:
Since my code for consuming the "test product" did not work correctly, so it never got consumed. Normally, I cover this issue by consuming all consumables listed in getPurchases at startup, but the "test product" is not returned in this list, so I could never consume it and had lost all information needed to be able to consume it. No other solution than to manually cancel the purchase, after many hours of working on my ulcer.

ISSUES TO WORK-AROUND:
(1) getProducts failing because of the "test product" not being consumed. Normal consumable products that have not been consumed, will not break getProducts.
(2) getPurchases not returning the "test product" if not consumed yet. All other non-consumed products are returned, just not this one as far as I can tell.

**Comment by richardmarais** [comment]
I am getting the same error when `.getProducts(this.PRODUCT_IDS)`:

> Error retrieving SKU details

It was working perfectly, until I added a test user. I tried to make a purchase with the test user.

    this.iap.buy(item.productId).then((data) => {
      return this.iap.consume(data.productType, data.receipt, data.signature);
    }).then(() => {
      console.log('product was successfully consumed!');

But now I cannot access the products any longer.

@JohnScottMcNerney says above that the reason may be because testers cannot consume a product and offers this solution:

SOLUTION:
Pull up "orders" on the Play Console and "cancel" the pending purchase.

However, then I have two questions:

1. How do you test purchases, if a tester cannot consume a product?
2. Where do you pull up orders on the Play Console? I do look at "Order Management", but there are no orders listed.

Thanks

**Comment by JohnScottMcNerney** [comment]
Personally, I punted trying to do "test" purchases. Too many problems. I found my IOS implementation using "test" purchases completely wrong when I finally got a real purchase.

I just make sure to have a $.99 item I can purchase, and do "real" purchases. It did not take too many to get my code working with the "real" data. I spent about $20 total, which I found reasonable. Note, I could have refunded these if I wanted, and did it with one, but didn't bother with the rest since I way paying myself (minus the store's cut).

This approach may not be for everyone, but I found the "test purchase" support on both Google and Apple stores to be lacking.

**Comment by richardmarais** [comment]
Thanks JohnScottMcNerney. I think I will follow the same approach as you. the "test" functionality on the Play Store does seem to be inadequate. 

In order to restore my state back to the way it was, i.e. so that I can `getProducts`, do you know how I can either "cancel" or "consume" the product that's blocking?

**Comment by JohnScottMcNerney** [comment]
@richardmarais sorry, I honestly don't remember. I was Google'ing about this issue, and found a reference about cancelling it, so I did. bookmarks.google.com is broken for me, so I can't see if I bookmarked it....

From Google : "Play Developer Console doesn’t currently support cancelation of test IAP. The only ways is to either consume the IAP or wait the 14 days consumption time."

**Comment by richardmarais** [comment]
Thanks for the advise John. Appreciate the help.

**Comment by richardmarais** [comment]
@JohnScottMcNerney, I have waited over 14 days now, and I still get the "Error retrieving SKU details". 

Strange thing is this works perfectly in iOS, on Android has the issue. So I think my code is correct.

Is there anywhere I can cancel the pending order?

**Comment by JohnScottMcNerney** [comment]
@richardmarais , sorry but I do not have a solution for you, but a couple of thoughts...

1) iOS does not require consumption, right? The consume routines are just place-holders for iOS and don't actually do anything, if I remember correctly. So, could it be a code issue?

2) Dig into the source-code for this module, and put in some debug statements where the actual "consume" calls/talks with Google. Surely Google does not just return an empty list if there is a non-consumed product, else one bad transaction would lock up an APP completely. Google may be returning something that this module is not expecting, so an empty list is the default returned. Painful to do this, but maybe it's worth it to find a solution.

3) Create a completely new APP on Google Play, that is a stripped down version with only the critical pieces (e.g. this module) for testing. If this works, and you can't get your main APP alive again, just create a new APP and start fresh. I have a "broken" APP on Google (not published) because I lost my keystore and had to start a new APP. Can't delete the "broken" APPs, just rename them to "broken". I also have a "push-notification" APP I use to test/debug a couple of different plugins, but I will never release this APP. I will just roll it's functionality into my main APP when I'm happy with it.

4) Never use emulators (probably not related), if possible. With Xcode (w/terminal plugin) and Chrome remote debugging for Android, I find no use for emulators. They seem to cause people more issues than they solve.

**Comment by MrVibe** [comment]
@richardmarais : The bug in Google android developer is causing this. My suggestion would be to login to google playstore from a different account (remove all other accounts) and try again. Just make sure inapppurchase is consuming the product.

**Comment by aerialglasgow** [comment]
@MrVibe - Yep this was the issue I had experienced. Not enough to create an additional google test account to use for Google Play beta testing, best to Remove All other Google Accounts, especially if it is your main developer account. Restart device might be required also, worked for me. Cheers.
