### ISSUE TITLE
App rejected for IPv6?

### ISSUE THREAD

**Issue by loqoio** [AlexDisler/cordova-plugin-inapppurchase#65]
Hello

After submitting to iTunes Connect, Apple rejected the app with below reason, any idea what this means?

(Phonegap cli-6.3.0)

Thanks for your help.

From Apple
        2. 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1

We discovered one or more bugs in your app when reviewed on an iPhone running iOS 9.3.5 on Wi-Fi connected to an IPv6 network.
- During review we were unable to complete the offered In-App Purchase 

We've attached screenshot(s) for your reference.

Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

**Comment by Rcapuani** [comment]
I've had same result, post-review I tested on IPv6 network myself and reproduced what they reported.

**Comment by marcusforsberg** [comment]
Are you using server side receipt validation or is everything happening client side in your apps?

**Comment by Rcapuani** [comment]
Client side only for my app - to add more, functionality over an IPV6 network was fine when the app was built for and run on Android.

**Comment by pkyburz** [comment]
I had the same issue. It appeared to fail in retrieving the products as prices were not displayed. Is the inapppurchase plugin IPv6 compliant?

**Comment by Rcapuani** [comment]
Not exactly answering your question but: I solved my problem by switching to the other plugin.

**Comment by pkyburz** [comment]
Ok, good to know that it works :)

**Comment by TeKnoZ** [comment]
Can you please let me know which plugin have you switched to and it is working fine IPv6?

This is really irritating, I have 9 versions already published @ Google store, and yet trying to get iOS published! issue after another and another .. wonder when it will stop this Issues Series!

**Comment by Risingson** [comment]
Got the same issue. My app was approved without any issues before and i did not change anything on the IAP implementation.
Is there anything i can do apart from switching to another plugin?

**Comment by markoshust** [comment]
I'm using this plugin fine on IPv6. Found out this is Apple's general message if anything network-related isn't working (even properly connecting to the network/host, they will say it's an IPv6 issue when it's really not). I don't think there is anything wrong with this plugin.

**Comment by Risingson** [comment]
You are right. I re-submitted the exact same build and it got approved.

**Comment by jrmessias** [comment]
@Rcapuani 
I have the same problem and persist, what plugin you use?

**Comment by petrot** [comment]
My first release was approved, but the in-app-purccase items was not activated.. Then I activated them and uploaded a new version. Since then every version has been rejeceted. I tried to remove firebase (because it logged my purchases on android devices), but didn't help...

With simulator I got the following error and the buttons are disabled:
RMStore: restored transactions failed with error Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store

But when I run on real device, it works great (with sandbox user).

**Comment by jrmessias** [comment]
Hi, 

For IPv6 complications I tested like [Guide](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1) orients.

But Apple team rejected the app, so i sended screenshots with screens what they reported the error and configuration of device (iPhone), and my app has been **approved**.

For errors in-app-purchase I configured the account like my another [issue](https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/128)

I hope helped.

(Sorry my english)

**Comment by petrot** [comment]
For me, the ipv6 problem HAS BEEN SOLVED.

First of all, I use WkWebView plugin for iOS in my ionic2 project. I read that it could be the solution for the ipv6 problem, but Apple always rejected my code, because the button were always disabled (see code below).

Yesterday my app has been accepted.

In my code, the problem caused by the restorePurchases() function. 

My old code:

`this._inAppPurchase.restorePurchases().then((purchases) => {
            this._inAppPurchase.getProducts(this.inAppProductIds).then((products) => {
                for (let product of products) {
                    let level = product.productId.split('.').pop();
                    product.className = level;
                    product.bought = false;
                    this.inAppProducts[level] = product;
                }

                for (let purchase of purchases) {
                    let level = purchase.productId.split('.').pop();
                    this.inAppProducts[level].bought = true;
                }

                this.inAppListLoaded = true;
            })
            .catch((err) => {
                //
            });
        })
        .catch(function (err) {
            //
        });`

So I tried to load the existing purchases, after then I load the items. The purchase buttons were enabled/disabled according to the product.bought value. Initialy they were disabled. I don't know why, but the restorePurchases() doesn't work on Apple tests and the purchase buttons stacked disabled.

Now I removed the restorePurchases() call and simply get the product list with getProducts(). My buttons always enabled, and the program doesn't check the previous purchases.. Not perfect, but works.. When the user click on a previously purchased item, it will be restored for free.
